### ISSUE TITLE
Error following r200 installation instructions

### ISSUE THREAD

**Issue by Kukanani** [PercATI/RealSense_ROS#23]
Hello,

I'm having trouble running the r200 install script. I'm getting the following output when running install.sh:

https://gist.github.com/Kukanani/9c151ea436b27bea971c

As I continue, multiple files are unable to patch. I saw in Issue #1 that I can simply ignore this message, but I am also experiencing Issue #21 so I'm thinking that the two are linked.

Ubuntu 14.04, Intel i7

**Comment by thieri** [comment]
start the script via
sudo su
then ./install.sh

**Comment by PercATI** [comment]
did you manage?

**Comment by Kukanani** [comment]
Sorry, this did not solve the issue. I still got the same result.

**Comment by Kukanani** [comment]
`uname -a` gives
`Linux cyclops 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mtsakaguchi** [comment]
Hello,

I am also having problems running the r200 install script.

When I run: sudo ./install.sh

I get:

----------------------------------------------------
1. Installing Driver
----------------------------------------------------
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dpkg-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 535 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to find a source package for linux-image-3.10.24-g6a2d13a
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to find a source package for linux-image-3.10.24-g6a2d13a
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-headers-3.10.24-g6a2d13a
E: Couldn't find any package by regex 'linux-headers-3.10.24-g6a2d13a'
ds_uvcdriver/scripts/patch_ubuntu_uvc.sh: 10: cd: can't cd to linux-*
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/drivers/media/usb/uvc/uvc_driver.c b/drivers/media/usb/uvc/uvc_driver.c
|index 8c1826c..3c5b533 100644
|--- a/drivers/media/usb/uvc/uvc_driver.c
|+++ b/drivers/media/usb/uvc/uvc_driver.c
--------------------------
File to patch: 

I continue and multiple files are unable to patch. I'm concerned since even when I run dmesg, no Intel RealSense USB device is listed.

uname -a prints (Trying to get the r200 working on an NVIDIA Jetson TK1):

Linux tegra-ubuntu 3.10.24-g6a2d13a #1 SMP PREEMPT Fri Apr 18 15:56:45 PDT 2014 armv7l armv7l armv7l GNU/Linux

Any help is greatly appreciated!

**Comment by Kukanani** [comment]
Hello, I was finally able to get this to work by upgrading my kernel to version 3.19. The command I ran was 

    sudo apt-get install linux-generic-lts-vivid

I also had to go into Software and Updates and check the "Source Code" checkbox.
